config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'user_registrations' }
  resources :articles
  resources :topics
  resources :allergies
  resources :diets
  resources :feedbacks
  get '/about_us', to: 'about_us#index'
  resource :user_profiles
  resource :locales

  root to: 'articles#index'
  resources :recipes, :products
end

app/models/article.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: articles
#
#  id                 :bigint           not null, primary key
#  content            :text
#  image_content_type :string
#  image_file_name    :string
#  image_file_size    :integer
#  image_updated_at   :datetime
#  title              :string
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#  topic_id           :integer
#  user_id            :bigint
#
# Indexes
#
#  index_articles_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#

class Article < ApplicationRecord
  include ImageUploadable

  TITLE_MAX_LENGTH   = 100
  TITLE_MIN_LENGTH   = 1
  CONTENT_MAX_LENGTH = 10_000
  CONTENT_MIN_LENGTH = 1

  belongs_to :topic
  belongs_to :author, class_name: User.name, foreign_key: :user_id

  validates :title, :content, :user_id, presence: true

  validates :title,   length: { in: TITLE_MIN_LENGTH..TITLE_MAX_LENGTH }
  validates :content, length: { in: CONTENT_MIN_LENGTH..CONTENT_MAX_LENGTH }
end

app/controllers/articles_controller.rb
# frozen_string_literal: true

class ArticlesController < ApplicationController
  before_action :authenticate_user!, except: :index
  before_action :current_article, only: %i[show edit update destroy]
  before_action :authorize!

  def index
    @articles = Article.all
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to articles_path,
                  flash: { notice: 'Article was successfully created.' }
    else
      redirect_to new_article_path,
                  flash: { error: @article.errors.full_messages.to_sentence }
    end
  end

  def show; end

  def edit; end

  def update
    if @article.update(article_params)
      redirect_to article_path(@article),
                  flash: { notice: 'Article updated.' }
    else
      render :edit,
             flash: { error: @article.errors.full_messages.to_sentence }
    end
  end

  def destroy
    if @article.destroy
      redirect_to articles_path,
                  flash: { notice: 'Article deleted.' }
    else
      redirect_to article_path(@article),
                  flash: { error: @article.errors.full_messages.to_sentence }
    end
  end

  private

  def article_params
    params.require(:article).permit!
  end

  def current_article
    @article = Article.find(params[:id])
  end

  def authorize!
    authorize(@article || Article)
  end
end

app/views/articles/_articles_preview.html.haml
.row.justify-content-md-center.low-btn
  = link_to article.title, article_path(article), class: 'btn btn-primary'

app/views/articles/_form.html.haml
.container
  #intro
    .site-heading
      - if !@article.title.nil?
        = @article.title
      - else
        = t :write_article, scope: 'articles.new'
    #intro-image
  .card-body
    = simple_form_for(article) do |form|
      .form-label-group
        = form.input :topic_id, placeholder: 'Choose topic', label: (t :choose_topic, scope: 'articles.new') do
          = form.select :topic_id, options_for_select(      |
          Topic.all.map{ |topic| [topic.name, topic.id]}) |
        = form.input :user_id, as: :hidden, input_html: { value: current_user.id }
        = form.input :image, label: false, type: :file

        - if @article.image?
          = image_tag @article.image.url(:medium).to_s, class: 'img-form-for-pictures'

        = form.input :title, placeholder: (t :title, scope: 'articles.new'), label: false
        = form.input :content, placeholder: (t :content, scope: 'articles.new'), label: false, placeholder: true, as: :trix_editor
        .row.justify-content-md-center
          .col-md-auto
            = form.button :button, type: :submit, class: 'btn btn-primary'
  .row.justify-content-md-center.low-btn
    - if policy(@article).destroy?
      = button_to (t :delete, scope: 'articles'), @article, method: :delete, class: 'btn btn-primary'

app/views/articles/edit.html.haml
= render partial: "form", locals: { article: @article }

app/views/articles/index.html.haml
.container
  #intro
    .site-heading
      = t :articles, scope: 'articles.index'
      - if policy(:article).create?
        = button_to (t :new_article, scope: 'articles.index'), new_article_path, method: :get, class: 'btn btn-primary'
    #intro-image
  .row
    - @articles.each do |article|
      .col-md-5
        .p-2
          - if article.image?
            = image_tag article.image.url , class: 'img-form-for-pictures'
      .col-md-7
        .p-2
          %h3= link_to article.title, article_path(article), method: :get
          .ellipsis
            .overflow.ellipsis#articles_description_custom
              %p= article.content.html_safe
          %a= button_to (t :read, scope: 'articles.index'), article_path(article), method: :get, class: 'btn btn-primary'

app/views/articles/new.html.haml
= render partial: "form", locals: { article: @article }

app/views/articles/show.html.haml
.container
  #intro
    .site-heading
      = @article.title
      - if @article.image?
        = image_tag @article.image.url(:medium), class: 'img-form-for-pictures'
      .row
        - if policy(@article).update?
          = link_to (t :edit, scope: 'articles.show'), edit_article_path(@article), method: :get, class: 'btn btn-primary'
    #intro-image
  .section-header
    %p= @article.content.html_safe
  .row.justify-content-md-center
    .col-md-auto
      - if policy(@article).destroy?
        = link_to (t :delete, scope: 'articles'), @article, method: :delete, class: 'btn btn-primary'
  .row.justify-content-md-center.low-btn
    = link_to (t :all_articles, scope: 'articles.show'), articles_path, class: 'btn btn-primary'