config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'user_registrations' }
  resources :articles
  resources :topics
  resources :allergies
  resources :diets
  resources :feedbacks
  get '/about_us', to: 'about_us#index'
  resource :user_profiles
  resource :locales

  root to: 'articles#index'
  resources :recipes, :products
end

app/models/topic.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: topics
#
#  id          :bigint           not null, primary key
#  description :text
#  name        :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Topic < ApplicationRecord
  NAME_MAX_LENGTH        = 50
  NAME_MIN_LENGTH        = 1
  DESCRIPTION_MAX_LENGTH = 1_200
  DESCRIPTION_MIN_LENGTH = 1

  has_many :articles

  validates :name, :description, presence: true

  validates :name,        length: { in: NAME_MIN_LENGTH..NAME_MAX_LENGTH }
  validates :description, length: { in: DESCRIPTION_MIN_LENGTH..DESCRIPTION_MAX_LENGTH }
end

app/controllers/topics_controller.rb
# frozen_string_literal: true

class TopicsController < ApplicationController
  before_action :authenticate_user!, except: :index
  before_action :current_topic, only: %i[show edit update destroy]
  before_action :authorize!

  def index
    @topics = Topic.all
  end

  def new
    @topic = Topic.new
  end

  def create
    @topic = Topic.new(topic_params)

    if @topic.save
      redirect_to topic_path(@topic),
                  flash: { notice: 'Topic was successfully created.' }
    else
      redirect_to new_topic_path,
                  flash: { error: @topic.errors.full_messages.to_sentence }
    end
  end

  def show; end

  def edit; end

  def update
    if @topic.update(topic_params)
      redirect_to topic_path(@topic),
                  flash: { notice: 'Updated topic' }
    else
      render :edit,
             flash: { error: @topic.errors.full_messages.to_sentence }
    end
  end

  def destroy
    if @topic.destroy
      redirect_to topics_path,
                  flash: { notice: 'Deleted topic' }
    else
      redirect_to topic_path(@topic),
                  flash: { error: @topic.errors.full_messages.to_sentence }
    end
  end

  private

  def topic_params
    params.require(:topic).permit(:name, :description, :user_id)
  end

  def current_topic
    @topic = Topic.find(params[:id])
  end

  def authorize!
    authorize(@topic || Topic)
  end
end

app/views/topics/_form.html.haml
%body
  #intro
    .site-heading
      = t :write_topic, scope: 'topics.new'
    #intro-image
  .card-body
    = simple_form_for(topic) do |form|
      .form-label-group
        = form.input :name, placeholder: (t :title, scope: 'topics.new'), label: false
        = form.input :description, placeholder: (t :description, scope: 'topics.new'), label: false
        .row.justify-content-md-center
          .col-md-auto
            = form.button :button, type: :submit, class: 'btn btn-primary'
  .row.justify-content-md-center.low-btn
    - if policy(@topic).destroy?
      = button_to (t :delete, scope: 'topics'), @topic, method: :delete, class: 'btn btn-primary'

app/views/topics/edit.html.haml
= render partial: "form", locals: {topic: @topic}, action: :edit

app/views/topics/index.html.haml
.container
  #intro
    .site-heading
      = t :topics, scope: 'topics.index'
      - if policy(:topic).create?
        = button_to (t :new_topic, scope: 'topics.index'), new_topic_path, method: :get, class: 'btn btn-primary'
    #intro-image
  .row
    - @topics.each do |topic|
      .col-md-5
        .p-2
          %a{href: "#"}
            %img.img-fluid.rounded-circle{alt: "", src: "https://www.vibrantplate.com/wp-content/uploads/2018/05/Quinoa-buddha-bowl-03-720x720.jpg"}/
      .col-md-7
        .p-2
          %h3= link_to topic.name, topic_path(topic), method: :get
          .ellipsis
            .overflow.ellipsis
              %p= topic.description.html_safe
          %a= button_to (t :read, scope: 'topics.index'), topic_path(topic), method: :get, class: 'btn btn-primary'

app/views/topics/new.html.haml
= render partial: "form", locals: {topic: @topic}, action: :new

app/views/topics/show.html.haml
.container
  #intro
    .site-heading
      = @topic.name
      .row
        - if policy(:topic).update?
          = link_to (t :edit, scope: 'topics.show'), edit_topic_path(@topic), method: :get, class: 'btn btn-primary'
    #intro-image
  .section-header
    %p= @topic.description.html_safe
  .row.justify-content-md-center
    .col-md-auto
      = link_to (t :delete, scope: 'topics'), @topic, method: :delete, class: 'btn btn-primary'
  = render partial: 'articles/articles_preview', collection: @topic.articles, as: :article
  .row.justify-content-md-center.low-btn
    = link_to (t :all_topics, scope: 'topics.show'), topics_path, class: 'btn btn-primary'