config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'user_registrations' }
  resources :articles
  resources :topics
  resources :allergies
  resources :diets
  resources :feedbacks
  get '/about_us', to: 'about_us#index'
  resource :user_profiles
  resource :locales

  root to: 'articles#index'
  resources :recipes, :products
end

app/models/allergy.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: allergies
#
#  id                 :bigint           not null, primary key
#  description        :string
#  image_content_type :string
#  image_file_name    :string
#  image_file_size    :integer
#  image_updated_at   :datetime
#  name               :string
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#

class Allergy < ApplicationRecord
  include ImageUploadable

  NAME_MAX_LENGTH        = 50
  DESCRIPTION_MAX_LENGTH = 1_000

  has_many :restrictions, as: :restrictable

  accepts_nested_attributes_for :restrictions, reject_if: :all_blank, allow_destroy: true

  validates :name, :description, presence: true

  validates :name,        length: { maximum: NAME_MAX_LENGTH }
  validates :description, length: { maximum: DESCRIPTION_MAX_LENGTH }
end

app/controllers/allergies_controller.rb
# frozen_string_literal: true

class AllergiesController < ApplicationController
  before_action :authenticate_user!, except: :index
  before_action :current_allergy, only: %i[show edit update destroy]
  before_action :authorize!

  def index
    @allergies = Allergy.all
  end

  def show
    @recipes = RecipesByAllergyQuery.new(params[:id]).call
  end

  def new
    @allergy = Allergy.new
  end

  def create
    @allergy = Allergy.new(allergy_params)

    if @allergy.save
      redirect_to allergy_path(@allergy),
                  flash: { notice: 'Allergy was successfully created.' }
    else
      redirect_to allergies_path,
                  flash: { error: @allergy.errors.full_messages.to_sentence }
    end
  end

  def edit; end

  def update
    if @allergy.update(allergy_params)
      redirect_to allergy_path(@allergy),
                  flash: { notice: 'Updated allergy.' }
    else
      render :edit,
             flash: { error: @allergy.errors.full_messages.to_sentence }
    end
  end

  def destroy
    if @allergy.destroy
      redirect_to allergies_path,
                  flash: { notice: 'Deleted allergy.' }
    else
      render :edit,
             flash: { error: @allergy.errors.full_messages.to_sentence }
    end
  end

  private

  def allergy_params
    params.require(:allergy).permit!
  end

  def current_allergy
    @allergy = Allergy.find(params[:id])
  end

  def authorize!
    authorize(@allergy || Allergy)
  end
end

app/views/allergies/_form.html.haml
%body
  #intro
    .site-heading
      = t :title, scope: 'allergies.new'
    #intro-image
  .card-body
    = simple_form_for(allergy) do |f|
      .form-label-group
        = f.input :image, label: false, type: :file
        - if @allergy.image?
          = image_tag @allergy.image.url(:medium).to_s, class: 'img-form-for-pictures'
        = f.input :name, placeholder: (t :name, scope: 'allergies.new'), label: false
        = f.input :description, placeholder: (t :description, scope: 'allergies.new'), label: false
        = f.simple_fields_for :restrictions do |restriction|
          = render 'restrictions/restriction_fields', f: restriction
        .links
          = link_to_add_association (t :restriction, scope: 'allergies.new'), f,
            :restrictions, partial: '/restrictions/restriction_fields'
        .row.justify-content-md-center
          .col-md-auto
            = f.button :button, type: :submit, class: 'btn btn-primary'

app/views/allergies/edit.html.haml
= render 'form', allergy: @allergy

app/views/allergies/index.html.haml
.container
  #intro
    .site-heading
      = t :label, scope: 'allergies.index'
      - if policy(:allergy).create?
        = button_to (t :new_allergy, scope: 'allergies.index'), new_allergy_path, method: :get, class: 'btn btn-primary'
    #intro-image
  .row
    - @allergies.each do |allergy|
      .col-md-5
        .p-2
          - if allergy.image?
            = image_tag allergy.image.url(:medium), class: 'img-form-for-pictures'
      .col-md-7
        .p-2
          %h3= link_to allergy.name, allergy_path(allergy), method: :get

app/views/allergies/new.html.haml
= render 'form', allergy: @allergy

app/views/allergies/show.html.haml
.container
  #intro
    .site-heading
      = @allergy.name
      .row
        - if policy(:allergy).update?
          = button_to (t :edit, scope: 'allergies.show'), edit_allergy_path(@allergy), method: :get, class: 'btn btn-primary'
    #intro-image
.section-header
  %p= @allergy.description
  = render partial: 'restrictions/restriction',
    collection: @allergy.restrictions, as: :restriction
.row.justify-content-md-center
  .col-md-auto
    - if policy(:allergy).destroy?
      = button_to (t :remove, scope: 'allergies.show'), @allergy, method: :delete, class: 'btn btn-primary'
  #intro-image
.section-header
  %h4= t :recipes, scope: 'diets.show'
.row
  - @recipes.each do |recipe|
    .col-sm-3
      - if recipe.image?
        = image_tag recipe.image.url, class: 'img-form-for-pictures', id: 'round_recipe_image'
    .col-sm-9
      .p-2.text-center
        %h4.card-title.text-left
          = link_to recipe.name, recipe_path(recipe)
        .row
          .col.recepies_params.text-left
            = t :products_need, scope: 'recipes.show'
            = recipe.products.size
          .col.recepies_params.text-center
            = t :preparation_time, scope: 'recipes.show'
            = recipe.preparation_time
          .col.recepies_params.text-right
            = t :preparation_kind, scope: 'recipes.show'
            = recipe.preparation_kind
        .description.text-left.overflow.ellipsis
          = recipe.description
      .row.float-right
        %a= button_to (t :cook, scope: 'recipes.index'), recipe_path(recipe), method: :get, class: 'btn btn-primary float-right'