config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'user_registrations' }
  resources :articles
  resources :topics
  resources :allergies
  resources :diets
  resources :feedbacks
  get '/about_us', to: 'about_us#index'
  resource :user_profiles
  resource :locales

  root to: 'articles#index'
  resources :recipes, :products
end

app/models/diet.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: diets
#
#  id                 :bigint           not null, primary key
#  description        :string
#  image_content_type :string
#  image_file_name    :string
#  image_file_size    :integer
#  image_updated_at   :datetime
#  name               :string
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#  user_id            :bigint
#
# Indexes
#
#  index_diets_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#

class Diet < ApplicationRecord
  include ImageUploadable

  NAME_MAX_LENGTH        = 50
  DESCRIPTION_MAX_LENGTH = 1_000

  has_many :restrictions, as: :restrictable
  has_many :recommendations, as: :recommendationable

  belongs_to :author, class_name: User.name, foreign_key: :user_id

  accepts_nested_attributes_for :restrictions, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :recommendations, reject_if: :all_blank, allow_destroy: true

  validates :name, :description, :user_id, presence: true
  validates :name,        length: { maximum: NAME_MAX_LENGTH }
  validates :description, length: { maximum: DESCRIPTION_MAX_LENGTH }
end

app/controllers/diets_controller.rb
# frozen_string_literal: true

class DietsController < ApplicationController
  before_action :authenticate_user!, except: :index
  before_action :current_diet, only: %i[show edit update destroy]
  before_action :authorize!

  def index
    @diets = Diet.all
  end

  def show
    @recipes = RecipesByDietQuery.new(params[:id]).call
  end

  def new
    @diet = Diet.new
  end

  def create
    @diet = Diet.new(diet_params)
    if @diet.save
      redirect_to diets_path,
                  flash: { notice: 'Diet was successfully created.' }
    else
      redirect_to new_diet_path,
                  flash: { error: @diet.errors.full_messages.to_sentence }
    end
  end

  def edit; end

  def update
    if @diet.update_attributes(diet_params)
      redirect_to diet_path(@diet),
                  flash: { notice: 'Diet updated.' }
    else
      render :edit,
             flash: { error: @diet.errors.full_messages.to_sentence }
    end
  end

  def destroy
    if @diet.destroy
      redirect_to diets_path,
                  flash: { notice: 'Diet deleted.' }
    else
      redirect_to diet_path(@diet),
                  flash: { error: @diet.errors.full_messages.to_sentence }
    end
  end

  private

  def diet_params
    params.require(:diet).permit!
  end

  def current_diet
    @diet = Diet.find(params[:id])
  end

  def authorize!
    authorize(@diet || Diet)
  end
end

app/views/diets/edit.html.haml
#headline
  %h3= t :title, scope: 'diets.edit'
.container
  = simple_form_for(@diet, defaults: { required: false }) do |f|
    .row.mt-2
      .col-4.text-center.ml-2
        = f.input :image, as: :file, label: false, type: :file
        - if @diet.image.exists?
          = image_tag @diet.image.url, class: 'img-form-for-pictures'
      .col-6.form-label-group
        = f.input :user_id, as: :hidden, input_html: { value: current_user.id }
        = f.input :name, label: (t :name, scope: 'diets.new')
        = f.input :description, label: (t :description, scope: 'diets.new')
      .col-4.ml-2.form-label-group
        .links.text-center
          .d-block
            = link_to_add_association (t :restriction, scope: 'diets.new'), f, :restrictions,
              partial: '/restrictions/restriction_fields'
          .d-block
            = link_to_add_association (t :recommendation, scope: 'diets.new'), f, :recommendations,
              partial: '/recommendations/recommendation_fields'
      .col-6.text-left.ml-3
        = f.submit (t :update, scope: 'diets.edit'), :class => 'btn btn-outline-primary', :id=>'diet_buttons'

app/views/diets/index.html.haml
.container
  #intro
    .site-heading
      = t :title, scope: 'diets.index'
      - if policy(:diet).create?
        = button_to (t :new_diet, scope: 'diets.index'), new_diet_path, method: :get, :class => 'btn btn-outline-primary'
    #intro-image
  .row
    - @diets.each do |diet|
      .col-md-5
        .p-2
          - if diet.image?
            = image_tag diet.image.url(:medium), class: 'img-form-for-pictures'
      .col-md-7
        .p-2.text-left
          %h3= link_to diet.name, diet_path(diet)
          .row
            .col.recepies_params.text-left
              = t :recipes, scope: 'recipes.index'
              = RecipesByDietQuery.new(diet.id).recipes_count
          .description.text-left.overflow.ellipsis
            = diet.description
          %a= button_to (t :choose_diet, scope: 'diets.index'), diet_path(diet), method: :get, :class => 'btn btn-primary'

app/views/diets/new.html.haml
#headline-2
  %h3= t :title, scope: 'diets.new'
.container-fluid
  = simple_form_for(@diet, defaults: { required: false }, multipart: true) do |f|
    .row.mt-3
      .col-4.text-center
        %img.card-img-top-edit
        .links
          .d-block
            = link_to_add_association (t :restriction, scope: 'diets.new'), f, :restrictions,
              partial: '/restrictions/restriction_fields'
          .d-block
            = link_to_add_association (t :recommendation, scope: 'diets.new'), f, :recommendations,
              partial: '/recommendations/recommendation_fields'

      .col-5.form-label-group
        = f.input :image, as: :file, label: false, type: :file
        = f.input :user_id, as: :hidden, input_html: { value: current_user.id }
        = f.input :name, label: (t :name, scope: 'diets.new')
        = f.input :description, label: (t :description, scope: 'diets.new')
        = f.submit (t :create, scope: 'diets.new'), :class => 'btn btn-outline-primary', :id=>'diet_buttons'

app/views/diets/show.html.haml
#intro
  .site-heading
    = @diet.name
    - if @diet.image?
      = image_tag @diet.image.url(:medium), class: 'img-form-for-pictures'
    .row
      .col
        = t :recipes, scope: 'recipes.index'
        = @recipes.size
    .row
      .col
        - if policy(@diet).update?
          = button_to (t :edit, scope: 'diets.show'), edit_diet_path(@diet), method: :get, :class => 'btn'
      .col
        - if policy(@diet).destroy?
          = button_to (t :remove, scope: 'diets.show'), @diet, method: :delete, :class => 'btn'
  #intro-image
.section-header
  %h4= t :description, scope: 'diets.show'
  %p= @diet.description
  .row
    .col.text-left
      %h4= t :restrictions, scope: 'diets.show'
      %p= render partial: 'restrictions/restriction',      |
          collection: @diet.restrictions, as: :restriction |
    .col.text-left
      %h4= t :recommendations, scope: 'diets.show'
      %p=render partial: 'recommendations/recommendation',      |
          collection: @diet.recommendations, as: :recommendation |
  %h4= t :recipes, scope: 'diets.show'
.row
  - @recipes.each do |recipe|
    .col-sm-3
      - if recipe.image?
        = image_tag recipe.image.url, class: 'img-form-for-pictures', id: 'round_recipe_image'
    .col-sm-9
      .p-2.text-center
        %h4.card-title.text-left
          = link_to recipe.name, recipe_path(recipe)
        .row
          .col.recepies_params.text-left
            = t :products_need, scope: 'recipes.show'
            = recipe.products.size
          .col.recepies_params.text-center
            = t :preparation_time, scope: 'recipes.show'
            = recipe.preparation_time
          .col.recepies_params.text-right
            = t :preparation_kind, scope: 'recipes.show'
            = recipe.preparation_kind
        .description.text-left.overflow.ellipsis
          = recipe.description
      .row.float-right
        %a= button_to (t :cook, scope: 'recipes.index'), recipe_path(recipe), method: :get, class: 'btn btn-primary float-right'